bare(1)

# NAME

bare - vertical bar for Wayland

# SYNOPSIS

*bare* [options...]

# DESCRIPTION

bare is a vertical bar for Wayland compositors that support
the layer-shell and ext-workspace-v1 protocols.

# OPTIONS

*-h, --help*
	Show help message and quit.

*-c, --config*
	Set the config file location.

*-d, --debug*
	Enable debug output.

The bar is configured via a configuration file as described in *bare*(5).

# AUTHORS

Konstantin Pospelov <kupospelov@gmail.com>

# SEE ALSO

*bare*(5)
